version: '3.4'

services:

  dsrlearn_postgresql:
    image: postgres:14.1
    
  dsrlearn_rabbitmq:
    image: rabbitmq:management
            
  dsrlearn_api:
    image: ${DOCKER_REGISTRY-}dsrlearnapi
    build:
      context: .
      dockerfile: Systems/Api/DSRLearn.Api/Dockerfile
    depends_on:
      - dsrlearn_postgresql
      - dsrlearn_rabbitmq
 
  dsrlearn_identity:
    image: ${DOCKER_REGISTRY-}dsrlearnidentity
    env_file:
      - env.identity
    build:
      context: .
      dockerfile: Systems/Identity/DSRLearn.Identity/Dockerfile
    depends_on:
      - dsrlearn_postgresql
      - dsrlearn_api

  dsrlearn_worker_1:
    image: ${DOCKER_REGISTRY-}learnworker
    build:
      context: .
      dockerfile: Systems/Worker/DSRLearn.Worker/Dockerfile
    depends_on:
      - dsrlearn_rabbitmq
      - dsrlearn_api

  dsrlearn_worker_2:
    image: ${DOCKER_REGISTRY-}learnworker
    build:
      context: .
      dockerfile: Systems/Worker/DSRLearn.Worker/Dockerfile
    depends_on:
      - dsrlearn_rabbitmq
      - dsrlearn_api

  blazorclientserverclient:
    image: blazorclientserverclient
    build:
      context: .
      dockerfile: Systems/Web/DSRLearn.Web/Dockerfile
    ports:
      - 5080:80
      - 5443:443