version: '3.4'

services:
  dsrlearn_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "35432:5432"
    networks:
      - shared_dsrlearn_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  dsrlearn_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_dsrlearn_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq
    

  dsrlearn_api:
    ports:
      - "10000:8080"
    networks:
      - shared_dsrlearn_net
    env_file:
      - env.api

  dsrlearn_identity:
    ports:
      - "10005:8080"
    networks:
      - shared_dsrlearn_net
    env_file:
      - env.identity

  # dsrnetschool_worker_1:
  #   networks:
  #     - shared_netschool_net
  #   ports:
  #     - "10002:8080"
  #   env_file:
  #     - env.worker

  # dsrnetschool_worker_2:
  #   networks:
  #     - shared_netschool_net
  #   ports:
  #     - "10003:8080"
  #   env_file:
  #     - env.worker


networks:
  shared_dsrlearn_net:
    name: dsrlearn
    driver: bridge